<script setup>
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {Box,ChevronRight,Download,FileImage,Image,LogOut,Menu,RefreshCw,Save,Server,Settings,Trash2,Upload,WandSparkles,X} from 'lucide-vue-next'
import ModelViewer from './ModelViewer.vue'
const route=ref(location.pathname);const busy=ref(false),message=ref(''),error=ref(''),menu=ref(false)
const loginPassword=ref(''),loginBusy=ref(false)
const imageMode=ref('文字生成图片'),prompt=ref(''),source=ref(null),sourceUrl=ref(''),result=ref(null),images=ref([]),selectedImage=ref(null)
const views=reactive({front:null,back:null,left:null,right:null});const viewUrls=reactive({front:'',back:'',left:'',right:''});const material=ref('纯色无光照'),quality=ref('打印精度'),gpu=ref('自动选择'),task=reactive({id:'',status:'idle',stage:'等待任务'}),models=ref([]),selectedModel=ref(null)
const settings=reactive({compute_url:'',compute_token:'',sub2api_url:'',sub2api_key:'',image_model:'gpt-image-1'}),gpus=ref([]),modelsAvailable=ref([]),passwords=reactive({current:'',new:'',confirm:''})
const availableImageModels=computed(()=>[...new Set([settings.image_model,...modelsAvailable.value].filter(Boolean))])
const pages=[['/image','图片生成与编辑',Image],['/model','图片转 3D 模型',Box],['/settings','设置与配置',Settings]]
function navigate(path){history.pushState({},'',path);route.value=path;menu.value=false;if(path==='/image')loadImages();if(path==='/model'){loadModels();loadGpuStatus()}if(path==='/settings')loadSettings()}
window.addEventListener('popstate',()=>route.value=location.pathname)
async function api(path,options={}){const r=await fetch(path,options);if(r.status===401&&path!='/api/login'){location.href='/login';throw Error('请先登录')}let data={};try{data=await r.json()}catch{}if(!r.ok)throw Error(data.detail||`请求失败 (${r.status})`);return data}
function notify(text,isError=false){(isError?error:message).value=text;setTimeout(()=>{message.value='';error.value=''},4200)}
function pick(e,key){const f=e.target.files?.[0];if(!f)return;views[key]=f;if(viewUrls[key])URL.revokeObjectURL(viewUrls[key]);viewUrls[key]=URL.createObjectURL(f)}
function pickSource(e){source.value=e.target.files?.[0]||null;if(sourceUrl.value)URL.revokeObjectURL(sourceUrl.value);sourceUrl.value=source.value?URL.createObjectURL(source.value):''}
async function paste(target){try{const items=await navigator.clipboard.read();for(const item of items){const type=item.types.find(x=>x.startsWith('image/'));if(type){const blob=await item.getType(type),file=new File([blob],'clipboard.png',{type});if(target==='source'){source.value=file;sourceUrl.value=URL.createObjectURL(file)}else{views[target]=file;viewUrls[target]=URL.createObjectURL(file)}return}}throw Error('剪贴板中没有图片')}catch(e){notify(e.message,true)}}
async function loadImages(){try{images.value=(await api('/api/images')).items}catch(e){notify(e.message,true)}}
async function generateImage(){busy.value=true;try{const f=new FormData();f.append('prompt',prompt.value);f.append('mode',imageMode.value);if(source.value)f.append('source',source.value);const d=await api('/api/images/generate',{method:'POST',body:f});await loadImages();result.value=images.value.find(x=>x.id===d.item.id)||d.item;selectedImage.value=result.value;notify('图片生成完成')}catch(e){notify(e.message,true)}finally{busy.value=false}}
function chooseImage(item){selectedImage.value=item;result.value=item}
async function removeImage(item=selectedImage.value){if(!item||!confirm('确定删除这张图片？'))return;await api(`/api/images/${item.id}`,{method:'DELETE'});if(selectedImage.value?.id===item.id){selectedImage.value=null;result.value=null}await loadImages();notify('图片已删除')}
async function imageTo(target){if(!result.value)return;const blob=await fetch(result.value.url).then(r=>r.blob());const file=new File([blob],'generated.png',{type:blob.type});if(target==='edit'){imageMode.value='编辑图片';source.value=file;sourceUrl.value=URL.createObjectURL(file);navigate('/image');scrollTo({top:0,behavior:'smooth'})}else{views.front=file;viewUrls.front=URL.createObjectURL(file);navigate('/model')}}
async function loadModels(sync=false){try{models.value=(await api(`/api/models${sync?'?sync=true':''}`)).items}catch(e){notify(e.message,true)}}
async function loadGpuStatus(){try{gpus.value=(await api('/api/gpus')).gpus}catch{gpus.value=[]}}
async function generateModel(){if(!views.front)return notify('请上传主视图',true);busy.value=true;task.stage='正在上传图片并创建任务';task.status='running';try{const f=new FormData();f.append('material',material.value);f.append('quality',quality.value);f.append('gpu',gpu.value);for(const k of ['front','back','left','right'])if(views[k])f.append(k,views[k]);const d=await api('/api/models/generate',{method:'POST',body:f});task.id=d.task_id;pollTask()}catch(e){task.status='failed';task.stage=e.message;busy.value=false}}
async function pollTask(){try{const d=await api(`/api/tasks/${task.id}`);Object.assign(task,d);if(d.status==='complete'){busy.value=false;await loadModels();selectedModel.value=models.value[0]||null;notify('模型已保存到本机并载入预览');return}if(d.status==='failed'){busy.value=false;notify(d.stage||'生成失败',true);return}setTimeout(pollTask,2000)}catch(e){busy.value=false;task.status='failed';task.stage=e.message}}
async function removeModel(){if(!selectedModel.value||!confirm('确定删除这个模型？'))return;await api(`/api/models/${selectedModel.value.id}`,{method:'DELETE'});selectedModel.value=null;await loadModels()}
async function loadSettings(){const d=await api('/api/settings');Object.assign(settings,d,{compute_token:d.compute_token_saved?'********':'',sub2api_key:d.sub2api_key_saved?'********':''})}
async function saveCompute(){try{const d=await api('/api/settings/compute',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:settings.compute_url,token:settings.compute_token})});notify(d.message);settings.compute_token='********';settings.compute_token_saved=true}catch(e){notify(e.message,true)}}
async function testCompute(){try{const d=await api('/api/test/compute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:settings.compute_url,token:settings.compute_token})});gpus.value=d.gpus;notify(d.message)}catch(e){notify(e.message,true)}}
async function saveImageApi(){try{const d=await api('/api/settings/image',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:settings.sub2api_url,key:settings.sub2api_key,model:settings.image_model})});notify(d.message);settings.sub2api_key='********';settings.sub2api_key_saved=true}catch(e){notify(e.message,true)}}
async function testImageApi(){try{const d=await api('/api/test/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:settings.sub2api_url,key:settings.sub2api_key,model:settings.image_model})});modelsAvailable.value=d.models;if(d.models.length&&!d.models.includes(settings.image_model))settings.image_model=d.models[0];notify(d.message)}catch(e){notify(e.message,true)}}
async function changePassword(){try{const d=await api('/api/settings/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(passwords)});notify(d.message);setTimeout(()=>location.href='/login',800)}catch(e){notify(e.message,true)}}
async function logout(){await api('/api/logout',{method:'POST'});location.href='/login'}
async function doLogin(){loginBusy.value=true;error.value='';try{await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:loginPassword.value})});location.href='/image'}catch(e){notify(e.message,true)}finally{loginBusy.value=false}}
function size(n){return n>1048576?`${(n/1048576).toFixed(1)} MB`:`${Math.ceil(n/1024)} KB`}
function date(t){return new Date(t*1000).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
onMounted(()=>{if(route.value==='/login')return;if(!['/image','/model','/settings'].includes(route.value))navigate('/image');else if(route.value==='/image')loadImages();else if(route.value==='/model'){loadModels();loadGpuStatus()}else loadSettings()})
</script>

<template><div v-if="route==='/login'" class="login-page"><form @submit.prevent="doLogin"><div class="login-mark"><Box :size="24"/></div><h1>3D 创作工作台</h1><p>输入访问密码以继续</p><label>访问密码<input v-model="loginPassword" type="password" autofocus autocomplete="current-password"></label><button class="primary full" :disabled="loginBusy"><span v-if="loginBusy" class="spinner"></span>{{loginBusy?'验证中':'登录'}}</button><small v-if="error" class="login-error">{{error}}</small></form></div><div v-else class="shell"><aside :class="{open:menu}"><div class="brand"><span><Box :size="21"/></span><div><b>造物台</b><small>Hunyuan3D Studio</small></div></div><nav><button v-for="[path,label,Icon] in pages" :class="{active:route===path}" @click="navigate(path)"><component :is="Icon" :size="18"/><span>{{label}}</span><ChevronRight :size="16" class="chevron"/></button></nav><button class="logout" @click="logout"><LogOut :size="18"/>退出登录</button></aside><div class="shade" v-if="menu" @click="menu=false"></div><main><header class="topbar"><button class="icon mobile" @click="menu=true"><Menu/></button><div><h1>{{pages.find(x=>x[0]===route)?.[1]}}</h1><p>{{route==='/image'?'生成、修改并管理创作图片':route==='/model'?'从一张或多张图片构建可打印模型':'连接服务并管理持久化配置'}}</p></div></header>

<section v-if="route==='/image'" class="workspace image-page"><div class="form-pane"><div class="segmented"><button v-for="m in ['文字生成图片','编辑图片']" :class="{active:imageMode===m}" @click="imageMode=m">{{m}}</button></div><div v-if="imageMode==='编辑图片'" class="field"><label>待编辑图片</label><div class="upload-box compact" :style="sourceUrl?{backgroundImage:`url(${sourceUrl})`}:{}"><input type="file" accept="image/*" @change="pickSource"><Upload :size="24"/><span>{{source?'更换图片':'选择图片文件'}}</span></div><button class="secondary full" @click="paste('source')"><FileImage :size="17"/>从剪贴板读取</button></div><div class="field"><label>{{imageMode==='编辑图片'?'修改要求':'图片描述'}}</label><textarea v-model="prompt" rows="8" :placeholder="imageMode==='编辑图片'?'描述希望如何修改这张图片':'描述主体、造型、材质、视角与背景'"/></div><button class="primary full" :disabled="busy" @click="generateImage"><span v-if="busy" class="spinner"></span><WandSparkles v-else :size="18"/>{{busy?'正在生成':'生成图片'}}</button></div><div class="result-pane"><div class="section-head"><div><h2>生成结果</h2><p>选择历史记录也可继续编辑或转为模型</p></div></div><div class="image-result" :class="{filled:result}" :style="result?{backgroundImage:`url(${result.url})`}:{}"><div v-if="!result" class="empty"><Image :size="34"/><span>生成结果将在这里显示</span></div></div><div class="action-row"><button class="secondary" :disabled="!result" @click="imageTo('edit')">继续编辑</button><button class="primary" :disabled="!result" @click="imageTo('model')"><Box :size="17"/>用于生成 3D</button></div><div class="section-head history-title"><div><h2>历史图片</h2><p>{{images.length}} 项保存在本机</p></div><button class="icon" title="刷新" @click="loadImages"><RefreshCw :size="17"/></button></div><div class="history-list"><div v-for="item in images" :class="['history-item',{active:selectedImage?.id===item.id}]" role="button" tabindex="0" @click="chooseImage(item)" @keydown.enter="chooseImage(item)"><img :src="item.url"><span><b>{{item.mode}}</b><small>{{date(item.created)}} · {{size(item.size)}}</small><em>{{item.prompt||'旧版生成记录'}}</em></span><button class="row-delete" title="删除图片" @click.stop="removeImage(item)"><Trash2 :size="17"/></button></div><div v-if="!images.length" class="empty small">暂无图片记录</div></div><div class="action-row"><a :class="['button secondary',{disabled:!selectedImage}]" :href="selectedImage?selectedImage.url+'?download=true':null"><Download :size="17"/>下载</a><button class="danger" :disabled="!selectedImage" @click="removeImage()"><Trash2 :size="17"/>删除</button></div></div></section>

<section v-if="route==='/model'" class="workspace model-page"><div class="form-pane"><div class="section-head"><div><h2>上传物体视图</h2><p>主视图必填，增加任意角度图后自动使用多视图模型</p></div></div><div class="views"><label v-for="(label,key) in {front:'主视图 / 正面',back:'背面（可选）',left:'左侧（可选）',right:'右侧（可选）'}" :class="['view-upload',key==='front'?'main-view':'']" :style="viewUrls[key]?{backgroundImage:`url(${viewUrls[key]})`}:{}"><input type="file" accept="image/*" @change="pick($event,key)"><Upload :size="22"/><span>{{label}}</span><small>点击选择文件</small><button type="button" class="paste" title="从剪贴板读取" @click.prevent="paste(key)"><FileImage :size="15"/></button></label></div><div class="field"><label>材质</label><div class="choices"><button v-for="x in ['纯色无光照','PBR 材质','仅几何白模']" :class="{active:material===x}" @click="material=x">{{x}}</button></div></div><div class="field"><label>质量</label><div class="choices"><button v-for="x in ['快速预览','均衡','打印精度']" :class="{active:quality===x}" @click="quality=x">{{x}}</button></div></div><div class="field"><label>执行 GPU</label><select v-model="gpu"><option>自动选择</option><option v-for="g in gpus" :key="g.index">GPU {{g.index}}</option></select></div><button class="primary full" :disabled="busy" @click="generateModel"><span v-if="busy" class="spinner"></span><Box v-else :size="18"/>{{busy?'任务执行中':'开始生成模型'}}</button><div :class="['task-status',task.status]"><span :class="{spinner:task.status==='running'}"></span><div><b>{{task.status==='running'?'正在处理':task.status==='failed'?'任务失败':'任务状态'}}</b><p>{{task.stage}}</p></div></div></div><div class="result-pane"><div class="section-head"><div><h2>模型预览</h2><p>拖动旋转，滚轮缩放</p></div></div><ModelViewer :url="selectedModel?.url"/><div class="section-head history-title"><div><h2>历史模型</h2><p>{{models.length}} 项保存在本机</p></div><button class="icon" @click="loadModels(true)"><RefreshCw :size="17"/></button></div><div class="model-list"><button v-for="item in models" :class="['model-row',{active:selectedModel?.id===item.id}]" @click="selectedModel=item"><span class="model-icon"><Box :size="20"/></span><span><b>{{item.material||'3D 模型'}}</b><small>{{item.id}} · {{size(item.size)}}</small></span><em>{{item.elapsed?item.elapsed+' 秒':''}}</em></button><div v-if="!models.length" class="empty small">暂无模型记录</div></div><div class="action-row"><a :class="['button primary',{disabled:!selectedModel}]" :href="selectedModel?selectedModel.url+'?download=true':null"><Download :size="17"/>下载 GLB</a><button class="danger" :disabled="!selectedModel" @click="removeModel"><Trash2 :size="17"/>删除</button></div></div></section>

<section v-if="route==='/settings'" class="settings-page"><div class="settings-section"><div class="settings-heading"><Server/><div><h2>计算服务器</h2><p>Hunyuan3D 任务与 GPU 状态来源</p></div></div><div class="settings-form"><label>计算服务器地址<input v-model="settings.compute_url" placeholder="http://服务器地址:7863"></label><label>计算服务器令牌<input v-model="settings.compute_token" type="password" autocomplete="new-password" data-1p-ignore="true" data-lpignore="true"></label><div class="action-row"><button class="primary" @click="saveCompute"><Save :size="17"/>保存配置</button><button class="secondary" @click="testCompute">测试连接</button></div></div><div v-if="gpus.length" class="gpu-grid"><article v-for="g in gpus"><header><span>GPU {{g.index}}</span><b>{{g.name}}</b></header><div class="metric"><span>计算占用 <b>{{g.util}}%</b></span><progress :value="g.util" max="100"/></div><div class="metric"><span>显存 <b>{{(g.used/1024).toFixed(1)}} / {{(g.total/1024).toFixed(1)}} GB</b></span><progress :value="g.used" :max="g.total"/></div><footer>{{g.temp}} C <span>{{Number(g.power).toFixed(0)}} W</span></footer></article></div></div><div class="settings-section"><div class="settings-heading"><WandSparkles/><div><h2>图片 API</h2><p>用于文字生成图片和图片编辑</p></div></div><div class="settings-form"><label>Sub2API 地址<input v-model="settings.sub2api_url" placeholder="http://服务地址"></label><label>Sub2API 密钥<input v-model="settings.sub2api_key" type="password" autocomplete="new-password" data-1p-ignore="true" data-lpignore="true"></label><label>图片模型<select v-model="settings.image_model"><option v-for="m in availableImageModels" :key="m" :value="m">{{m}}</option></select></label><div class="action-row"><button class="primary" @click="saveImageApi"><Save :size="17"/>保存配置</button><button class="secondary" @click="testImageApi">测试并读取模型</button></div></div></div><div class="settings-section"><div class="settings-heading"><Settings/><div><h2>登录密码</h2><p>修改后所有现有会话将退出</p></div></div><div class="settings-form password-grid"><label>当前密码<input v-model="passwords.current" type="password"></label><label>新密码<input v-model="passwords.new" type="password"></label><label>确认新密码<input v-model="passwords.confirm" type="password"></label><button class="secondary" @click="changePassword">修改密码</button></div></div></section>
</main><transition name="toast"><div v-if="message||error" :class="['toast',{error}]">{{error||message}}</div></transition></div></template>
